[package]
name = "tiny"
version = "0.1.0"
authors = ["Daniel Wiberg <daniel@skillster.se>"]

build = "build.rs"

[dependencies]
libc = "0.2.16"
image = "0.10.3"
glutin = "0.13.1"

[build-dependencies]
gl_generator = "0.9.0"
