[package]
name = "tiny"
version = "0.1.0"
authors = ["Daniel Wiberg <daniel@skillster.se>"]

[dependencies]
libc = "0.2.16"
image = "0.10.3"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = "0.2.8"
user32-sys = "0.2.0"
kernel32-sys = "0.2.2"
shell32-sys = "0.1.1"
gdi32-sys = "0.2.0"